config/routes.rb
Rails.application.routes.draw do

  mount Thredded::Engine => '/forum'


  devise_scope :user do
    root 'user/registrations#new'
    get '/', to: 'user/registrations#new'
  end
  devise_for :users, controllers: {registrations: 'user/registrations'}
  resource :books, except: :show
  get "/users/:id", to: "user#show"
  get "/books", to: "books#index"
  get "/books/:id", to: "books#show"
  get "/my/books/", to: "books#my_books"
  get "/favourites", to: "books#fav_books"
  get "/favourites/add/:id", to: "books#make_favourite", as: "make_favourite"
  # delete "books/:id", to: "books#destroy", as: "delete_book"
  # get "book/:id", to: "books#edit", as: "edit_book"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  # belongs_to :user

  validates_presence_of :name, :author

end

app/models/favorite_book.rb
class FavoriteBook < ApplicationRecord
  belongs_to :user
  belongs_to :book

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :books
  has_many :favorite_books
  has_many :fav_books, through: :favorite_books, source: "book"

  validates_presence_of :name

  def admin
    if self.id == 1
      return true
    end
    false
  end

  def to_s
    email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(user)
    "/books"
  end

  def check_book_owner(book)
    if book.user_id != current_user.id
      redirect_to my_books_path, notice: "You can't alter others book"
    end
    
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all.order(:id)
    @fav_books = current_user.fav_books
  end

  def new

    @book = Book.new

  end

  def create
    @book = current_user.books.new(book_params)
    respond_to do |format|
      if @book.save
        format.html {redirect_to my_books_path, notice: "Your book is successfully created"}
      else

        format.html { render :new }
      end
    end
  end

  def edit
    @book = Book.find(params[:format])
    check_book_owner(@book)
  end

  def update
    @book = Book.find(params[:book][:id])
    respond_to do |format|

      if @book.update_attributes(book_params)
        format.html { redirect_to my_books_path, notice: "Your book is successfully updated" }
      else
        format.html { render :edit }
      end
    end

  end

  def destroy
    @book = Book.find(params[:format])
    check_book_owner(@book)

    # respond_to do |format|
      if @book.delete
        redirect_to my_books_path, notice: "Your book is successfully deleted"
      else
        redirect_to my_books_path, notice: "unable to delete your book"
      end



  end

  def my_books

    @books = current_user.books.order(:id)

  end

  def fav_books
    @books = current_user.fav_books
  end

  def make_favourite

    book = Book.find(params[:id])
    fav_book =  current_user.fav_books.include?(book)
    message = "#{book.name} successfully "
    if fav_book
      FavoriteBook.where(book_id: params[:id], user_id: current_user.id).delete_all
      message += "removed from "
    else
      FavoriteBook.create(book_id: params[:id], user_id: current_user.id)
      message += "added to "
    end
    message += "favourites list"
    redirect_to books_path, notice: message
  end

  private

  def book_params
    params.require(:book).permit(:name, :author, :description)

  end

end

app/controllers/user/confirmations_controller.rb
class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute, :name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user_controller.rb
class UserController < ApplicationController


  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/books/_form.html.erb
<div class="container">
  <%= form_for(book, url: books_path) do |b| %>
      <div class="panel panel-default ">
        <div class="panel-heading">
          <h2 class="panel-title"> New Book</h2>
        </div>
        <div class="panel-body">
          <% if book.errors.any? %>
              <div id="error_explanation" class="alert alert-danger">
                <ul>
                  <% book.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>
          <%= b.hidden_field :id %>

          <div class="form-group">
            <%= b.label :name %>
            <%= b.text_field :name, autofocus: true, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= b.label :author %>
            <%= b.text_field :author, autofocus: true, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= b.label :description %>
            <%= b.text_area :description, autofocus: true, class: "form-control" %>
          </div>

          <div class="actions form-group">
            <%= b.submit "Submit", class: "btn btn-primary" %>
          </div>
        </div>
      </div>
      </div>

  <% end %>
  </div>

app/views/books/_list.html.erb
<table>
  <thead>
    <th>Sl.no</th>
    <th>Name</th>
    <th>Author</th>
    <th>Description</th>
  </thead>

  <tbody>
  <% row = 0%>
  <% @books.each do |book| %>
    <tr>
      <td>
        <%= row += 1%>
      </td>
      <td>
        <%= book.name%>
      </td>
      <td>
        <%= book.author%>
      </td>
      <td>
        <%= book.description%>
      </td>
    </tr>
  <%end%>
  </tbody>
</table>

app/views/books/edit.html.erb
<h2>Edit</h2>
<%= render "form", book: @book%>

app/views/books/fav_books.html.erb
<h1>My Books</h1>

<%= link_to "Add New", new_books_path %>
<table class="table">
  <thead>
  <th>Sl.no</th>
  <th>Name</th>
  <th>Author</th>
  <th>Description</th>
  </thead>

  <tbody>
  <% row = 0%>
  <% @books.each do |book| %>
      <tr>
        <td>
          <%= row += 1%>
        </td>
        <td>
          <%= book.name%>
        </td>
        <td>
          <%= book.author%>
        </td>
        <td>
          <%= book.description%>
        </td>
      </tr>
  <%end%>
  </tbody>
</table>

app/views/books/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <!--<div class="panel panel-default">-->
    <br>
    <div class=" panel-heading">
      <div class="row">
        <div class="col-sm-4">
          <h2>Books</h2>
        </div>
        <div class="col-sm-8 panel-control align-rignt">


        </div>
      </div>

    </div>
    <div class="table-responsive">
      <table class="table table-responsive table-bordered">
        <thead>
        <th>Sl.no</th>
        <th>Name</th>
        <th>Author</th>
        <th>Description</th>
        <th>Favourite</th>
        </thead>

        <tbody>
        <% row = 0 %>
        <% @books.each do |book| %>
            <tr>
              <td>
                <%= row += 1 %>
              </td>
              <td>
                <%= book.name %>
              </td>
              <td>
                <%= book.author %>
              </td>
              <td>
                <%= book.description %>
              </td>
              <td>
                <% fav = @fav_books.include? book %>
                <% message = fav ? "Do you want to remove #{book.name} from your favourites list" : "Do you want to add #{book.name} to your favourites list" %>
                <%= link_to (check_box_tag "favourite", !fav, fav), make_favourite_path(book), data: {confirm: message} %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <!--</div>-->
  </div>
</div>

app/views/books/my_books.html.erb
<h1>My Books</h1>

<%= link_to "Add New", new_books_path %>
<table class="table">
  <thead>
  <th>Sl.no</th>
  <th>Name</th>
  <th>Author</th>
  <th>Description</th>
  <th>Actions</th>
  </thead>

  <tbody>
  <% row = 0%>
  <% @books.each do |book| %>
      <tr>
        <td>
          <%= row += 1%>
        </td>
        <td>
          <%= book.name%>
        </td>
        <td>
          <%= book.author%>
        </td>
        <td>
          <%= book.description%>
        </td>
        <td>
          <%= button_to "Edit", edit_books_path(book), method: :get, class: "btn btn-primary"%>
          <%= button_to "Delete", books_path(book), method: :delete, class: "btn btn-danger"%>
        </td>
      </tr>
  <%end%>
  </tbody>
</table>

app/views/books/new.html.erb
<%= render "form", book: @book%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookcart</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<% if user_signed_in? %>
    <nav class="navbar navbar-default" role="navigation">
      <div class="navbar-brand">Bookcart</div>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", "/books" %></li>
          <li><%= link_to "Your Books", my_books_path %></li>
          <li><%= link_to "Favourites", favourites_path %></li>
          <li><%= link_to "Forum", "/forum" %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        </ul>
      </div>
    </nav>
<% end %>
<%= yield %>
</body>
</html>

app/views/user/show.html.erb
<% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "alert alert-success bodyLeftPadd" %>
<% end %>
<div class="container bodyPadd">
  <div class="col-sm-6 col-sm-offset-3 user-profile">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title text-center">Profile</h3></div>
      <div class="panel-body">

        <dl class="dl-horizontal">
          <dt><b>Name</b></dt>
          <dd><%= @user.name %></dd>
        </dl>

        <dl class="dl-horizontal">
          <dt><b>Email</b></dt>
          <dd><%= @user.email %></dd>
        </dl>
        
      </div>
      <div class="panel-footer text-center">
        <%= link_to 'Back', :back, class: "btn btn-primary" %>
      </div>
    </div>


  </div>
</div>